### ISSUE TITLE
XInput Battery Information

### ISSUE THREAD

**Issue by mchiasson** [dmadison/ArduinoXInput#29]
I am essentially building a wireless controller using a teensy 3 with ArduinoXInput, and would like to report the battery level to the host, which can be consumed as described in this api doc
https://docs.microsoft.com/en-us/windows/win32/api/xinput/ns-xinput-xinput_battery_information

However, I am not exactly sure how to modify ArduinoXInput to provide battery type and level information. Perhaps you can help?

Thanks!

**Comment by dmadison** [comment]
The USB descriptors in the "boards" repositories emulate a wired controller which has no battery, so I doubt that it's possible as is. You would likely have to reverse engineer one of the wireless Xbox controllers and its wireless adapter, and then create your own USB implementation for the Teensy that interfaces with the library's API.
