### ISSUE TITLE
Using XInput.press within GamepadPins

### ISSUE THREAD

**Issue by VirtualDude777** [dmadison/ArduinoXInput#31]
I have been testing my home made joystick with your lib and it works great!  Had no problems following your guide. The Blink example (XInput.press/release) works fine, and GamepadPins too.   

I am trying to add a "Turbo" button within a sketch based from GamepadPins (even reverted to the original example and just try to add a press/release). It seems the press/release command that works fine alone (Blink) is not effective within GamepadPins.  Probably because buttons were mapped differently but I cannot figure out how to do it.

Blink code:

	XInput.press(BUTTON_A);
	delay(1000);

	XInput.release(BUTTON_A);
	delay(1000);

Thank you!

**Comment by dmadison** [comment]
It's not that the buttons are mapped differently, it's that they're already set in the sketch. Lines 145-158:

```cpp
	// Set XInput buttons
	XInput.setButton(BUTTON_A, buttonA);
	XInput.setButton(BUTTON_B, buttonB);
	XInput.setButton(BUTTON_X, buttonX);
	XInput.setButton(BUTTON_Y, buttonY);

	XInput.setButton(BUTTON_LB, buttonLB);
	XInput.setButton(BUTTON_RB, buttonRB);

	XInput.setButton(BUTTON_BACK, buttonBack);
	XInput.setButton(BUTTON_START, buttonStart);

	XInput.setButton(BUTTON_L3, buttonL3);
	XInput.setButton(BUTTON_R3, buttonR3);
```

If you want to control the button outputs yourself you need to remove the relevant `setButton` calls, else they'll overwrite any previous calls to `press` or `release`.

**Comment by VirtualDude777** [comment]
Thank you! Did a quick test, not working for now but you gave me a good hint, I'll work around that. Thanks again!

**Comment by dmadison** [comment]
Could you elaborate on what you're trying to accomplish? Maybe I can help.

**Comment by VirtualDude777** [comment]
I found out that removing this line (or set to true) solved the problem.  

//  XInput.setAutoSend(false);  // Wait for all controls before sending

Any PRESS / RELEASE done after XInput.send(); is not processed properly (even with XInput.setButton line active) My goal was to create a Turbo button (PRESS, delay 25, RELEASE) when a button is pressed but any attempt like the BLINK sketch was not working.

**Comment by VirtualDude777** [comment]
As an example (at the end og GamepadPins), this will work if AutoSend=true, but not if set to false. 

  // Send control data to the computer
  XInput.send();

  XInput.press(BUTTON_X);
  delay(50);

  XInput.release(BUTTON_X);
  delay(50);

**Comment by dmadison** [comment]
Yeah that'll do it, although bear in mind for the GamepadPins example you're sending a packet (4ms delay) for every function call with that option off, which will add considerable delay.

The better solution if you want to support more than one button is not to use `delay()` at all so that the rest of the inputs are processed normally, and instead use the built-in timekeeping functions to flip the output. Look up the Arduino example "BlinkWithoutDelay" [(link)](https://www.arduino.cc/en/tutorial/BlinkWithoutDelay). But more or less:

```cpp
boolean state = false;  // unpressed, global
unsigned long lastSwitch = 0;  // timestamp, global
unsigned long swapTime = 25;  // ms
...
if(digitalRead(button) == LOW) {  // button held
	if(millis() - lastSwitch >= swapTime) {
		state = !state;  // flip output
		lastSwitch = millis();  // save timestamp
	}
	XInput.setButton(BUTTON_A, state);
}
else {
	state = false;  // unpressed
}
```

**Comment by VirtualDude777** [comment]
The delay does affect the whole loop and performance.  I will have a look at this option, exactly what I need :-)

Thanks again, your XInput project is great!  Will use on a Nintendo switch (with USB adapter to support Xbox controller).  Much easier compared to the Nintendo switch libs I have seen out there.
