### ISSUE TITLE
Bluetooth support?

### ISSUE THREAD

**Issue by wolfshow** [dmadison/ArduinoXInput#32]
Is it possbile to support bluetooth board such as hc-05 or esp32?

**Comment by dmadison** [comment]
Theoretically, yes. Someone would need to reverse engineer the Xbox One controller and figure out how to get the ESP to emulate it, then build an API wrapper to integrate with the library.

I am not going to add wireless support myself. I have no experience developing with Bluetooth and I don't have to hardware to experiment with it.

**Comment by Rmdhn1** [comment]
Theoretically it is, but needs a usb dongle, use a compatible board as a usb dongle and another sending the values

**Comment by Rmdhn1** [comment]
If you wanna be cheeky look into controller emulation softwares and send HID data, as in keypresses and mouse movements, some even allow them to differentiate between "keyboards" and "mouse" so you can still use your main keyboard while using the emulated Arduino one

**Comment by EloiStree** [comment]
> Is it possible to support Bluetooth modules like the HC-05 or ESP32?

I'm not sure whether this information will help future developers who come across this project.

For reference, here’s a related project that uses an HC-05 over UART for remote control:
https://github.com/EloiStree/2023_06_21_ArduinoToX360

I’d love to create a fresh version using an ESP32-S3, but issue #69 indicates that this topic is closed and not planned.
