### ISSUE TITLE
Arduino DUE support

### ISSUE THREAD

**Issue by baritonomarchetto** [dmadison/ArduinoXInput#33]
Not an issue but a request: could this project extend the compatibility to include arduino DUE board?

Thanks for the great piece of code!

**Comment by dmadison** [comment]
See my response to #27. If someone else wanted to build support I'd be happy to link back to it, but I currently have no plans to build an XInput core for those boards.

**Comment by baritonomarchetto** [comment]
Unfortunately it's far from my capability. Thanks for the great work so far! ;)
