### ISSUE TITLE
Xbox One compatibility

### ISSUE THREAD

**Issue by EdoardoBaggio** [dmadison/ArduinoXInput#57]
I was wondering if this arduino library is compatible with xbox one console, so can I emulate a controller directly connecting it on the console or is it only compatible with pc?

**Comment by dmadison** [comment]
[Please read the documentation.](https://github.com/dmadison/ArduinoXInput#console-support)

>Please be aware that none of the currently available board packages support connecting to the console itself. Genuine controllers use a dedicated hardware security chip that handshakes with the console. Arduinos do not have this chip, and its security method has not been (openly) broken.
