### ISSUE TITLE
XInput.h not found

### ISSUE THREAD

**Issue by henryfoster** [dmadison/ArduinoXInput#77]
Error message: 

```
C:\Users\andre\Blink\Blink.ino:31:10: fatal error: XInput.h: No such file or directory
 #include <XInput.h>
          ^~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: XInput.h: No such file or directory
```

Code (selected from examples):
```
#include <XInput.h>

void setup() {
	XInput.begin();
}

void loop() {
	XInput.press(BUTTON_A);
	delay(1000);

	XInput.release(BUTTON_A);
	delay(1000);
}

```

Installed https://github.com/dmadison/ArduinoXInput_AVR
installed 1.2.6
selected as board Arduino Micro w/ XInput

**Comment by dmadison** [comment]
Hello. That error indicates that the library is not installed correctly. Do you see the library listed in the "examples" dropdown in the IDE?

**Comment by dmadison** [comment]
More information needed, closing as stale.

**Comment by henryfoster** [comment]
Hi, sorry for the silence. 

> Do you see the library listed in the "examples" dropdown in the IDE?

Yes I did. 

The problem seems to be with Windows11. I switched to a second PC with Win10 and it worked flawless.
