### ISSUE TITLE
bluetooth feature

### ISSUE THREAD

**Issue by Narsku** [dmadison/ArduinoXInput#78]
can you add bluetooth to the project?, or can you just help us adding force feedback in this project? https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/137
Thanks in advance.

**Comment by dmadison** [comment]
Hello. This project is focused on the USB XInput implementation, Bluetooth support is another animal altogether. I have done no work reverse engineering the Xbox's Bluetooth protocol and I am unable to help you.

Sorry!

**Comment by LeeNX** [comment]
@Narsku if you looking for BlueTooth XInput take a look at https://github.com/Mystfit/ESP32-BLE-CompositeHID.
