### ISSUE TITLE
Not able to get teensy board to have xinput mode Help

### ISSUE THREAD

**Issue by Europa284** [dmadison/ArduinoXInput#84]
I have been trying everything I can to use this for a xbox controller. Used directions as close as i can. installed older 1.x versions of arduino and teensyduino 1.58 and still xinput does not show up. The instructions say to copy files to the hardware folder, which I did in the 1.x versions, but the 2.08 version does not have a hardware folder.  Please help.
PS I am using the teensy 4.0 board.

**Comment by dmadison** [comment]
Hello, and sorry to hear that you're having trouble.

I've just updated the Teensy board documentation and added a note about where to find the hardware folder for the 2.x IDE. Although the 2.x IDE is still quite buggy at the moment and I would not recommend it, especially for this project.

If you cannot get the XInput mode to show up for the 1.x IDE I'm afraid there's not much I can do to help or troubleshoot. The files must be placed in the right folder and overwrite the existing ones from the vanilla Teensy core.
