### ISSUE TITLE
error: recipe.preproc.macros pattern is missing

### ISSUE THREAD

**Issue by strunx** [dmadison/ArduinoXInput#85]
hi,

to get xinput working on TeensyLC i have done following:

1. clean install Arduino IDE 1.8.19
2. install Teensyduino 1.57
3. start Arduino IDE 1.8.19 and install ArduinoXInput library 1.2.6 (currently compatible with Teensyduino Version 1.57)
4. get the special ArduinoXInput_Teensy files (Version 1.1.1 to make it compatible with Tennsyduino Version 1.57)
5. delete the vanilla "teensy"-folder in C:\Program Files (x86)\Arduino\hardware and 
6. replace it with the "teensy"-folder from special ArduinoXInput_Teensy files
7. start arduino IDE 1.8.19 and set Board "Teensy LC" with USB-type "xinput" and when compiling
8. this error-massage is displayed:  "recipe.preproc.macros pattern is missing" error compiling

What i am doing wrong?

Thx for help.

**Comment by dmadison** [comment]
>delete the vanilla "teensy"-folder in C:\Program Files (x86)\Arduino\hardware

This is wrong. Do not delete the folder, you need to copy the XInput modifications over the existing files.

**Comment by strunx** [comment]
hi Dave,

 


thank you for your quick reply.
so i have to put the individual files into the correspondent
folder, one file by one .... and not the whole folder...

 

best regards

 

strunx

 

 

 

Gesendet: Dienstag, 18. April 2023 um 21:25 Uhr
Von: "Dave Madison" ***@***.***>
An: "dmadison/ArduinoXInput" ***@***.***>
Cc: "strunx" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [dmadison/ArduinoXInput] error: recipe.preproc.macros pattern is missing (Issue #85)


 


delete the vanilla "teensy"-folder in C:\Program Files (x86)\Arduino\hardware


This is wrong. Do not delete the folder, you need to copy the XInput modifications over the existing files.

**Comment by dmadison** [comment]
You can copy the entire folder, you just need to replace the existing files.

The ArduinoXInput_Teensy repository only contains the handful of files in the core that need to be replaced. From your description it sounds like you are deleting the rest of the core files preemptively.

**Comment by strunx** [comment]
all works now. Thank you!
