### ISSUE TITLE
XInput.getRumbleLeft() and XInput.getRumbleRight() byte structure

### ISSUE THREAD

**Issue by baritonomarchetto** [dmadison/ArduinoXInput#86]
Hello Dave, this is not an issue but a help request :)

I am trying to figure out what is the structure of the rumble byte the library returns when the functions XInput.getRumbleLeft() and XInput.getRumbleRight() are called.

I suppose the byte could include the pad number, in example. How could I isolate the bare rumble intensity (frequency?) value?

Thanks in advance for the help!

**Comment by dmadison** [comment]
`XInput.getRumbleLeft()` and `XInput.getRumbleRight()` return a single byte (0-255) representing the intensity of the rumble. There is no fancy encoding going on.

**Comment by baritonomarchetto** [comment]
Thanks Dave!
