### ISSUE TITLE
Not issue: I just want to tip my hat.

### ISSUE THREAD

**Issue by EloiStree3D** [dmadison/ArduinoXInput#88]
Man,
I just wanted to say thank you.  

I am using your code to implement a tool that allows to test Xbox game on the XBox with TTL and HC06.  
![image](https://github.com/dmadison/ArduinoXInput/assets/106495897/50a57542-6423-4a23-a7a4-c5f1454e492c)

Your code works like charm, it is easy to understand with what is needed of documentation.  

Very nice :)

**Comment by dmadison** [comment]
❤️
