### ISSUE TITLE
is it possible to use a bluetooth module（like hc06)、Pro Micro together with XInput to make gamepad wireless?

### ISSUE THREAD

**Issue by assguard** [dmadison/ArduinoXInput#92]
is it possible to use a bluetooth module（like hc06)、Pro Micro together with XInput to make gamepad wireless?
Now I only got a pro mirco and diy-gamepad, i wonder can it be wireless :)

**Comment by dmadison** [comment]
Sort-of.

It's not possible to make the HC-06 (or whatever wireless device of your choosing) behave as an Xbox gamepad wirelessly using this library. This library mimics a USB gamepad, which must be wired.

It *is* possible to get whatever data you want for your gamepad, send it wirelessly using the HC-06 (or whatever wireless device of your choosing) to another Arduino board, and then have *that* board work as an XInput USB gamepad. I know some controller builders have done that in the past, although it's certainly not the most elegant solution.
